<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-01-16T23:44:46Z" name="Default suite" finished-at="2019-01-16T23:44:51Z" duration-ms="5109">
    <groups>
    </groups>
    <test started-at="2019-01-16T23:44:46Z" name="Default test" finished-at="2019-01-16T23:44:51Z" duration-ms="5109">
      <class name="com.app.tests.APIBasicTestsReview">
        <test-method signature="basicTest()[pri:0, instance:com.app.tests.APIBasicTestsReview@f2ff811]" started-at="2019-01-16T23:44:46Z" name="basicTest" finished-at="2019-01-16T23:44:49Z" duration-ms="2975" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicTest -->
        <test-method signature="getWithHeaders()[pri:0, instance:com.app.tests.APIBasicTestsReview@f2ff811]" started-at="2019-01-16T23:44:49Z" name="getWithHeaders" finished-at="2019-01-16T23:44:49Z" duration-ms="218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getWithHeaders -->
        <test-method signature="negativeGet()[pri:0, instance:com.app.tests.APIBasicTestsReview@f2ff811]" started-at="2019-01-16T23:44:49Z" name="negativeGet" finished-at="2019-01-16T23:44:50Z" duration-ms="262" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
this is wrong expected [202] but found [404],
this is wrong expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
this is wrong expected [202] but found [404],
this is wrong expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.app.tests.APIBasicTestsReview.negativeGet(APIBasicTestsReview.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeGet -->
        <test-method signature="printRequestBody()[pri:0, instance:com.app.tests.APIBasicTestsReview@f2ff811]" started-at="2019-01-16T23:44:50Z" name="printRequestBody" finished-at="2019-01-16T23:44:50Z" duration-ms="330" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- printRequestBody -->
        <test-method signature="verifyCOntentTYpeWithAssertThat()[pri:0, instance:com.app.tests.APIBasicTestsReview@f2ff811]" started-at="2019-01-16T23:44:50Z" name="verifyCOntentTYpeWithAssertThat" finished-at="2019-01-16T23:44:50Z" duration-ms="237" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCOntentTYpeWithAssertThat -->
        <test-method signature="verifyFirstName()[pri:0, instance:com.app.tests.APIBasicTestsReview@f2ff811]" started-at="2019-01-16T23:44:50Z" name="verifyFirstName" finished-at="2019-01-16T23:44:51Z" duration-ms="992" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFirstName -->
      </class> <!-- com.app.tests.APIBasicTestsReview -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
